export enum PostFeedActionTypes {
  GET_SOME_FEED_POSTS = 'GET_SOME_FEED_POSTS',
  IS_FETCHING_FEED_POSTS = 'IS_FETCHING_FEED_POSTS',
  IS_FETCHING_FEED_POSTS_FAILED = 'IS_FETCHING_FEED_POSTS_FAILED'
}
