export enum ProfilePostActionTypes {
  IS_FETCHING_USER_POSTS = 'IS_FETCHING_USER_POSTS',
  IS_FETCHING_USER_POSTS_SUCCESS = 'IS_FETCHING_USER_POSTS_SUCCESS',
  IS_FETCHING_USER_POSTS_FAILED = 'IS_FETCHING_USER_POSTS_FAILED',
  IS_CREATING_NEW_PROFILE_POSTS = 'IS_CREATING_NEW_PROFILE_POSTS',
  NEW_POST_FAILED = 'NEW_POST_FAILED',
  NEW_POST_SUCCESS = 'NEW_POST_SUCCESS',
  PROFILE_POSTS = 'PROFILE_POSTS',
  NEW_PROFILE_POSTS = 'NEW_PROFILE_POSTS',
  DELETING_PROFILE_POSTS = 'DELETING_PROFILE_POSTS',
  DELETING_PROFILE_POSTS_FAILED = 'DELETING_PROFILE_POSTS_FAILED',
  DELETING_PROFILE_POSTS_SUCCESS = 'DELETING_PROFILE_POSTS_SUCCESS',
  IS_EDITING_POST = 'IS_EDITING_POST',
  EDITING_POST_SUCCESS = 'EDITING_POST_SUCCESS',
  EDITING_POST_FAILED = 'EDITING_POST_FAILED'
}
