export enum SessionActionTypes {
  LOGOUT = 'LOGOUT',
  LOGIN_SIGNUP_SUCCESS = 'LOGIN_SIGNUP_SUCCESS',
  IS_LOGGING_IN_OR_SIGNING_UP = 'IS_LOGGING_IN_OR_SIGNING_UP',
  SIGNUP_LOGIN_FAILED = 'SIGNUP_LOGIN_FAILED'
}
