export enum SessionActionTypes {
  LOGOUT = 'LOGOUT',
  LOGIN_SIGNUP_SUCCESS = 'LOGIN_SIGNUP_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  SIGNUP_FAILED = 'SIGNUP_FAILED',
  IS_LOGGING_IN_OR_SIGNING_UP = 'IS_LOGGING_IN_OR_SIGNING_UP'
}
