export enum GameGroupActionTypes {
  GET_SOME_GAME_GROUPS = 'GET_SOME_GAME_GROUPS',
  IS_FETCHING_SOME_GAME_GROUPS = 'IS_FETCHING_SOME_GAME_GROUPS',
  IS_FETCHING_GAME_GROUPS_FAILED = 'IS_FETCHING_GAME_GROUPS_FAILED',
  IS_FETCHING_GAME_GROUPS_SUCCESS = 'IS_FETCHING_GAME_GROUPS_SUCCESS'
}
