export enum GameGroupItemActionTypes {
  SET_IS_FOLLOWING = 'SET_IS_FOLLOWING',
  FETCHING_GAME_GROUP_ITEM = 'IS_FETCHING_GAME_GROUP_ITEM',
  GAME_GROUP_ITEM_FETCH_SUCCESS = 'GAME_GROUP_ITEM_FETCH_SUCCESS',
  GAME_GROUP_ITEM_FETCH_FAILED = 'GAME_GROUP_ITEM_FETCH_FAILED',
  CURRENTLY_FOLLOWING_GAME_GROUP = 'CURRENTLY_FOLLOWING_GAME_GROUP',
  GAME_GROUP_ITEM_FOLLOWED_SUCCESS = 'GAME_GROUP_ITEM_FOLLOWED_SUCCESS',
  GAME_GROUP_ITEM_FOLLOWED_FAILED = 'GAME_GROUP_ITEM_FOLLOWED_FAILED',
  CURRENTLY_UNFOLLOWING_GAME_GROUP = 'CURRENTLY_UNFOLLOWING_GAME_GROUP',
  GAME_GROUP_ITEM_UNFOLLOWED_SUCCESS = 'GAME_GROUP_ITEM_UNFOLLOWED_SUCCESS',
  GAME_GROUP_ITEM_UNFOLLOWED_FAILED = 'GAME_GROUP_ITEM_UNFOLLOWED_FAILED'
}
