name: pull-request
on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-20.04
    name: run test
    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - name: setup env file
        run: |
          touch .env.test

          echo REACT_APP_COOKIE_NAME=_ggpo_tokz >> .env

      - name: install packages
        run: npm install
      - name: run tests
        run: npm test
